@MASPLQA.PGM: @masplqa.pgm.rpgle
@QUSRSPLA.PGM: @qusrspla.pgm.rpgle
CNVRSCDIR0.PGM: cnvrscdir0.pgm.rpgle MRSCDTA.FILE MHEADER.FILE
CHGRPT.0.PGM: chgrpt.0.pgm.rpgle MOPTVCT.FILE SPYCTL.FILE RSECUR.FILE
CPYRDR.PGM: cpyrdr.pgm.sqlrpgle MFLDDIR.FILE MRPTRSC.FILE RLNKNDX.FILE RDSTHST.FILE RSEGHDR.FILE RSEGMNT.FILE MNOTDIR.FILE
DEVI5.MODULE: devi5.rpgle MFLDDIR.FILE RAPFDBF.FILE
EXPOBJ.PGM: expobj.pgm.sqlrpgle AHYPLNKD.FILE CHYPIDXD.FILE DRPTIDXD.FILE MRPTDIR.FILE MIMGDIR.FILE
KEYCODEWEB.PGM: keycodeweb.pgm.sqlrpgle SPYKEYMST.FILE SPYKEYMST.FILE SPYKEYNOT.FILE SPYKEYMST1.FILE
LNKDBSQL0.MODULE: lnkdbsql0.sqlrpgle
LNKDBSQL1.MODULE: lnkdbsql1.sqlrpgle
KEYWEB2.PGM: keyweb2.pgm.sqlrpgle SPYKEYMST.FILE SPYKEYMST.FILE SPYKEYMST1.FILE
DSPHYPLNK0.PGM: dsphyplnk0.pgm.rpgle AHYPLNKD.FILE CHYPIDXD.FILE MIMGDIR.FILE
LNKDBSQLO.MODULE: lnkdbsqlo.sqlrpgle
MAG1090.0.PGM: mag1090.0.pgm.rpgle
MAG1091.0.PGM: mag1091.0.pgm.rpgle
MAG1060.0.PGM: mag1060.0.pgm.rpgle RSUBSCR.FILE RSUBLST.FILE RDSTDEF.FILE MIMGDIR.FILE
MAG602.PGM: mag602.pgm.rpgle RBNDDEF.FILE MAG601A.FILE
MAG8001.0.PGM: mag8001.0.pgm.sqlrpgle MAG8012.PGM WVPROP.FILE WVSECP.FILE WVTRAP.FILE WVTADP.FILE WVSPYP.FILE WVLDDP.FILE SPYCTL.FILE
MAG210.0.PGM: mag210.0.pgm.rpgle SPYCSNOT.PGM MIMGDIR.FILE MFLDDIR.FILE RPTABLE.FILE RPRTDJE.FILE RBNDBAN.FILE RBNDINS.FILE SPYCTL.FILE RWINDOW.FILE
MCDOCHITR.PGM: mcdochitr.pgm.rpgle
MFSPYAUTR0.MODULE: mfspyautr0.sqlrpgle SPYCTL.FILE
MFSPYAUTR1.MODULE: mfspyautr1.sqlrpgle SPYCTL.FILE
MFSPYKEYR0.PGM: mfspykeyr0.pgm.sqlrpgle SPYCTL.FILE
MAG2038.0.PGM: mag2038.0.pgm.rpgle SPYEXPSPC.PGM SPC2PRT.PGM SPYCSNOT.PGM RWINDOW.FILE RFORMS.FILE RPRTDJE.FILE MIMGDIR.FILE RSEGMNT.FILE RDSTHST.FILE RDSTDEF.FILE RAPFDBF.FILE MFLDDIR.FILE
MFSPYKEYR1.PGM: mfspykeyr1.pgm.sqlrpgle SPYCTL.FILE
MFSPYKEYR2.PGM: mfspykeyr2.pgm.rpgle SPYCTL.FILE
MGEMLTST.PGM: mgemltst.pgm.sqlrpgle
MGEMLSLT.0.PGM: mgemlslt.0.pgm.sqlrpgle RSUBLST.FILE RSUBLHD.FILE RSUBSCR.FILE
MGHITCNT.0.PGM: mghitcnt.0.pgm.sqlrpgle
MGHITCNT.PGM: mghitcnt.pgm.sqlrpgle DRPTIDXD.FILE
MGHITCNT0.PGM: mghitcnt0.pgm.sqlrpgle DRPTIDXD.FILE
MGHITCNTH.PGM: mghitcnth.pgm.rpgle
MGPRTPDF.0.PGM: mgprtpdf.0.pgm.sqlrpgle RPTABLE.FILE
MGNFSUSR.0.PGM: mgnfsusr.0.pgm.sqlrpgle
OMNITEST.PGM: omnitest.pgm.sqlrpgle DRPTIDXD.FILE MRPTDIR.FILE MIMGDIR.FILE
MRFLDDTA.PGM: mrflddta.pgm.sqlrpgle
MOVRDR.PGM: movrdr.pgm.rpgle MFLDDIR.FILE MRPTDES.FILE
PDFDST.0.MODULE: pdfdst.0.rpgle
SLASHDIRCT.PGM: slashdirct.pgm.rpgle
SPYCSLNK.PGM: spycslnk.pgm.sqlrpgle
SPYSVHIT.0.PGM: spysvhit.0.pgm.rpgle
SSLSOCK.PGM: sslsock.pgm.rpgle
SPYCSNOT.PGM: spycsnot.pgm.sqlrpgle RSEGMNT.FILE RSEGHDR.FILE MIMGDIR.FILE MNOTDIR.FILE MNOTDTA.FILE
TESTACCESS.PGM: testaccess.pgm.rpgle
SPYCS.0.PGM: spycs.0.pgm.rpgle SPYCSNOT.PGM
UNZIP.PGM: unzip.pgm.rpgle
TESTMERG.PGM: testmerg.pgm.sqlrpgle WCPWDP.FILE RLNKOFF.FILE
WRKSPI.PGM: wrkspi.pgm.sqlrpgle SPYCSLNK.PGM MOPTTBL.FILE MIMGDIR.FILE RLNKOFF.FILE RDBKEY.FILE RSEGHDR.FILE
@LNKDBSQL1.MODULE: @lnkdbsql1.pgm.rpgle
MCSPYHITR0.MODULE: mcspyhitr0.pgm.rpgle