CVTSEC.PGM: cvtsec.pgm.sqlrpgle
OBJSEC.FILE: objsec.pf
OBJSEC1.FILE: objsec1.lf OBJSEC.FILE
OBJSEC2.FILE: objsec2.lf OBJSEC.FILE
OBJSEC4.FILE: objsec4.lf OBJSEC.FILE
OBJSEC3.FILE: objsec3.lf OBJSEC.FILE
OBJSEC5.FILE: objsec5.lf OBJSEC.FILE