MAG8704.0.PGM: mag8704.0.pgm.rpgle RSPLCFG.FILE MIFSMON.FILE MIFSEXT.FILE RINDEX.FILE
MAG1505.PGM: mag1505.pgm.rpgle MIMGDIR.FILE MFLDDIR.FILE
CFMAIN.0.PGM: cfmain.0.pgm.sqlrpgle MRPTDIR.FILE MIMGDIR.FILE
MAG8012.PGM: mag8012.pgm.rpgle WVPROP.FILE WVTADP.FILE WVTRAP.FILE WVSECP.FILE