   PERFORM OVERRIDE TO FILE MEMBER AND THEN RUN VIA INTERACTIVE SQL

   WHERE CONDITION WILL BE DIFFERENT FOR EVERY FILE.
   RUN DISINTCT(LEFT(SRCDTA,5)) TO DETERMINE EXCLUSIONS.

UPDATE PREAD/QRPGSRC SET SRCDTA = '     ' || SUBSTR(SRCDTA,6,
LENGTH(SRCDTA)-5+ 1) WHERE LEFT(SRCDTA,1) <> '/' AND LEFT(SRCDTA,5)
NOT IN ('** ER', 'ERR10')
