SELECT RPTTYP AS REPORT_TYPE, CASE WHEN APFTYP = ' ' THEN 'SCS'
WHEN APFTYP = '1' THEN 'IPDS/ADVSCS' WHEN APFTYP = '2' THEN
'AFPDS/USERASCII' WHEN APFTYP = '3' THEN 'PCL' WHEN APFTYP = '4'
THEN 'NATIVE PDF' END AS FORMAT, COUNT(*) AS COUNTS FROM MRPTDIR
GROUP BY ROLLUP(APFTYP,RPTTYP) UNION SELECT IDRTYP AS REPORT_TYPE,
'IMAGE' AS FORMAT, SUM(IDICNT) AS COUNTS FROM MIMGDIR GROUP BY
ROLLUP(IDRTYP) ORDER BY FORMAT,REPORT_TYPE
